### ISSUE TITLE
 during build process

### ISSUE THREAD

**Issue by tolgahanbeyazoglu** [nuxt-modules/icon#105]
Hello, I am getting this error during the build process. 
![1252525](https://github.com/nuxt-modules/icon/assets/129540736/84961e74-2ff4-4a88-abdc-ec82d6325bd7)
What would be the reason?

**Comment by ExEr7um** [comment]
You have path: `.../Masa\xFCst\xFC/nuxt-js-web/...`. What are `\xFCst\xFC` symbols? I think it could be related to https://github.com/nuxt/nuxt/issues/15113.
