### ISSUE TITLE
Cannot read properties of undefined (reading 'aliases')

### ISSUE THREAD

**Issue by Sass2221** [nuxt-modules/icon#114]
version `nuxt-icon: 0.6.0 (last update)`
version `nuxt: 3.8.0`

I'm getting this error: `Cannot read properties of undefined (reading 'aliases')`
I rolled back 0.5.0 version. and it worked. don`t bugs

**Comment by JohnCampionJr** [comment]
just wasted an hour trying to find this....workaround is to make an app.config.ts with nuxtIcon: {}

**Comment by MagmaBlock** [comment]
same problem

**Comment by notflip** [comment]
@JohnCampionJr So app.config.ts should be a new file in the root?

**Comment by skribascode** [comment]
@notflip 
Thanks, this solution working !

**Comment by mathix420** [comment]
Seems to be fixed now https://github.com/nuxt-modules/icon/releases/tag/v0.6.1
