### ISSUE TITLE
Support for i-mdi-home "unocss" format

### ISSUE THREAD

**Issue by TechAkayy** [nuxt-modules/icon#115]
This is a follow-up of the previously implemented feature request - https://github.com/nuxt-modules/icon/issues/84

The correct format is `i-mdi-home`, but it looks like the [feature](https://github.com/nuxt-modules/icon/pull/95/files#diff-50150fdb79af08fa9f0d115a3d94ba246e9bf691e798b754b91c2472bccd9731R25) was implemented to support `i-mdi:home`. The full list of formats can be found here - https://github.com/antfu/icones/blob/main/src/utils/case.ts#L35

![image](https://github.com/nuxt-modules/icon/assets/73772701/7b951b2b-3198-4d22-aeeb-ea67eda71f9b)

**Comment by Atinux** [comment]
Not 100% sure that Iconify actually support this format when using it.

**Comment by TechAkayy** [comment]
No worries. The i-mdi:home format is good enough 👍🏽 thanks!

**Comment by Atinux** [comment]
With latest release, v0.6.3 you should be able to use the same format as UnoCSS without any issue!
