### ISSUE TITLE
Terminal errors and browser warnings in 0.6.2

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt-modules/icon#118]
Getting terminal errors and browser console warnings when upgrading from `0.6.1` to `0.6.2` for icons with names `ph:table` and `ph:code`:

![Screenshot 2023-11-06 at 15 54 56](https://github.com/nuxt-modules/icon/assets/2703233/ae697148-4633-4492-8300-048206d738e8)

<img width="1145" alt="Screenshot 2023-11-06 at 15 53 50" src="https://github.com/nuxt-modules/icon/assets/2703233/b08783d5-66d2-4809-837a-469b33b378b3">

**Comment by Atinux** [comment]
Should be fixed in v0.6.3 :)

**Comment by toniengelhardt** [comment]
Thanks, that was fast 🙏🏽 🙏🏽 🙏🏽

**Comment by toniengelhardt** [comment]
Hey @Atinux, it looks like the problem is actually still there in v0.6.3:

<img width="1161" alt="Screenshot 2023-11-06 at 19 14 08" src="https://github.com/nuxt-modules/icon/assets/2703233/7a5005fd-ca91-4099-8a85-0dc0b3476179">

Also, aliases like `'brand': 'IconBrand'` with a global component named `IconBrand.vue` are now not working anymore.

**Comment by Atinux** [comment]
Damn I did not expect people to use alias -> components 😅 

Fixed in `v0.6.5`

Also I do not have any warning locally, you can run the `playground/` I added a case for it: https://github.com/nuxt-modules/icon/blob/c206f6e7105f92507b8d4f280eea3e0f8467a355/playground/app.vue#L49-L53

**Comment by toniengelhardt** [comment]
It seems resolved now 🙏🏽

Of course, alias -> components is one of the best features ;)
