### ISSUE TITLE
v0.6.6 has problems with uppercase alias names

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt-modules/icon#125]
In `v0.6.5` this works:

```ts
nuxtIcon: {
  aliases: {
    'aws': 'IconAWS',
    // ...
  }
}
```

if there is a component in global named `IconAWS.vue`, but in `v0.6.6` it breaks. The reason is the uppercase naming, if I rename the component and the alias to `IconAws.vue` it works.

**Comment by Atinux** [comment]
Might be related to https://github.com/nuxt/nuxt/pull/24318

Could you confirm with the latest Nuxt version?

**Comment by toniengelhardt** [comment]
@Atinux I still see it in `nuxt@3.8.2`.

**Comment by Atinux** [comment]
Damn, I suspect it comes from `scule` update that transform `IconAWS` to `IconAws`.

Could you check with latest Nuxt version and look at the devtools to see your components names?

**Comment by toniengelhardt** [comment]
Sorry for the delay @Atinux, got taken down by the flu...

I'm not sure what exactly changed, but it seems to be working now. 

Closing 🙏🏽

**Comment by toniengelhardt** [comment]
@Atinux I'm seeing issues again with `nuxt 3.8.2` and `nuxt-icon 0.6.7`. The icons render locally but not in prod on Vercel with `node 18.x`. It seems like the problem occurs if there is a second capital letter in the component name, e.g. `IconCohere` or `IconPerplexity` works, but `IconAi21` and `IconNlpCloud` does not work.

Config: 

```ts
nuxtIcon: {
  aliases: {
    'cohere': 'IconCohere',
    'nlpcloud': 'IconNlpCloud', 
  }
}
```

From devtools:

<img width="555" alt="Screenshot 2023-12-24 at 16 12 19" src="https://github.com/nuxt-modules/icon/assets/2703233/40b45460-01d5-4b99-85f6-25816e801129">
