### ISSUE TITLE
Unexpected value 1.5rem parsing width attribute.

### ISSUE THREAD

**Issue by CommanderGL** [nuxt-modules/icon#141]
When using nuxt icon with width and height attributes i get the following warning:
```
Unexpected value 1.5rem parsing width attribute.
```

**Comment by Atinux** [comment]
Could you please share a reproduction on StackBlitz please?

**Comment by CommanderGL** [comment]
I can't reproduce this on stackblitz because when using stackblitz rem doesn't even render.

**Comment by CommanderGL** [comment]
In this case
