### ISSUE TITLE
import.meta.glob as: 'raw' fails

### ISSUE THREAD

**Issue by stepanenko3** [nuxt-modules/icon#145]
### Describe the bug

` WARN  The glob option "as" has been deprecated in favour of "query". Please update as: 'raw' to query: '?raw', import: 'default'.`

nuxt-icon.vue:23
```js
    const iconsImport = import.meta.glob('assets/icons/**/**.svg', {
      as: 'raw',
      eager: false
    })
```

When removing the { as: `raw` }, the error disappears.

**Comment by stepanenko3** [comment]
sorry, related to another package

**Comment by mrc-bsllt** [comment]
> sorry, related to another package

I got the same warning, what was it due to?

**Comment by robert-luoqing** [comment]
I got same issue. has it been resolved?
