### ISSUE TITLE
We are planning to use IconCSS feature to use css instead of SVG to reduce function, is IconCss stable?

### ISSUE THREAD

**Issue by BroJenuel** [nuxt-modules/icon#149]
Hi! we are planning to use IconCSS to reduce Dom stuffs and to at least improve performance of the website.. But I would love to know if the feature is stable for production stuffs. Thanks 🙂

**Comment by Atinux** [comment]
Yes you can use IconCSS @BroJenuel, it won't be removed and is considered stable.
