### ISSUE TITLE
iconifyApiOptions custom API not working

### ISSUE THREAD

**Issue by leosin** [nuxt-modules/icon#153]
I didn't quite understand that iconifyApiOptions in the document is only used to provide CDN for the default official api, or it can provide its own icon.

For example:
First, I made sure that my custom API was written according to the official version and can be accessed normally.

https://localhost:3000/fal.json?icons=house

However, when I set the options below, it didn't work. Only when publicApiFallback:false is set will it work properly.

```js
iconifyApiOptions: {
   url: 'http://localhost:3000',
   publicApiFallback: true,
},
```
<Icon name="fal:house" /> // not working

-------------

Finally, when I was writing this question, I took a look at the nuxt-icon source code and found this snippet.
```
  if (appConfig.nuxtIcon?.iconifyApiOptions?.publicApiFallback) {
     addAPIProvider('custom', {
       resources: [appConfig.nuxtIcon?.iconifyApiOptions.url],
       index: 0
     })
     return
   }
```
<Icon name="@custom:fal:house" /> // it works fine

**Comment by Atinux** [comment]
Could you please now with the new version? https://github.com/nuxt-modules/icon/releases/tag/v1.0.0-beta.1

**Comment by leosin** [comment]
Thank you very much for the prompt update, now it works.

But there will be a `warn`
```bash
WARN [Icon] Collection myicon is not found locally
We suggest to install it via npm i -D @iconify-json/myicon to provide the best end-user experience.
```
In other words, do I still need to make a local package? I am not very sure.

**Comment by antfu** [comment]
Ah, that's a good point. We could probably disable the warning when a custom end point is provided.
