### ISSUE TITLE
How to set the stroke-width?

### ISSUE THREAD

**Issue by Rednas83** [nuxt-modules/icon#159]
Tried:
```
  <Icon name="feather:home" color="green" size="20%" stroke-width="2" />
  <Icon name="feather:home" color="green" size="20%" stroke-width="2px" />
  <Icon name="feather:home" color="green" size="20%" :stroke-width="'2'" />
  <Icon name="feather:home" color="green" size="20%" :stroke-width="'2px'" />
  <Icon name="feather:home" color="green" size="20%" style="stroke-width: 2" ; />
  <Icon name="feather:home" color="green" size="20%" style="stroke-width: 2px" />
```

**Comment by Atinux** [comment]
I am not sure this feature is supported though

**Comment by Rednas83** [comment]
Looks like it's not although the icon set itself has support for it.
[image: image.png]

Would it be possible to add support for it?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by antfu** [comment]
Iconify doesn't support that: https://iconify.design/docs/icon-components/svg-framework/dimensions.html. And I am not even sure it's possible for Iconify to do that in a universal way - I think you might use a iconset that supports pre-defined storke variants.

**Comment by Rednas83** [comment]
Looking at the website it is supported for some icon sets actually
https://icon-sets.iconify.design/feather/home/
![image](https://github.com/nuxt-modules/icon/assets/25219229/3c79e220-8320-452e-94f1-a73a91cab53c)

Perhaps it can be achieved with
```
import { appendCustomStyle } from 'iconify-icon';
appendCustomStyle('svg [stroke-width="2"] { stroke-width: 1.5; }');
```
More info at https://github.com/iconify/iconify/issues/196

**Comment by laurensiusadi** [comment]
Leave it here for reference

`app.config.ts`
```
export default defineAppConfig({
  icon: {
    customize(content: string) {
      return content.replace(/stroke-width="[^"]*"/g, `stroke-width="2"`)
    },
  }
})

```

And in `nuxt.config.ts` set mode to SVG.
```
  icon: {
    mode: 'svg',
  },
```
