### ISSUE TITLE
Double svg tag when using custom collection

### ISSUE THREAD

**Issue by mfazail** [nuxt-modules/icon#165]
## Project deps
```json
"nuxt": "^3.11.2",
"nuxt-icon": "^1.0.0-beta.4"
```

## Problem 
When i use custom collection the generated svg code contains double tags something like 👇

```html
<svg ...>
    <svg ...>
          <path  ... />
    </svg>
</svg>
```

## Stackblitz 
[Reproduction link](https://stackblitz.com/edit/nuxt-starter-6nnfpa?file=app.vue)

### Svg Mode
![image](https://github.com/nuxt-modules/icon/assets/80394548/13b49201-a0d2-4f21-b0b7-205ddb14b53e)

### Css mode
![image](https://github.com/nuxt-modules/icon/assets/80394548/60c1a858-25b7-43de-8367-f9e114fd959e)

**Comment by alvarosabu** [comment]
![Screenshot 2024-05-25 at 16 44 27](https://github.com/nuxt-modules/icon/assets/4699008/8227d903-fe72-4739-bd88-2a99dee4df31)

Same here, they also get cropped constantly, even if the viewbox size is the same as in the config

**Comment by joseanzacarias** [comment]
If this works for someone I was having the same error about the icon getting cropped so I remove width and height from my own svg and now its fine. @alvarosabu  this could help you.

**Comment by mfazail** [comment]
@joseanzacarias hi, 
I have tried what you said but for some reason it doesn’t work on all svg.
