### ISSUE TITLE
Color Props should be added to documentation aswell

### ISSUE THREAD

**Issue by QaahirStewart** [nuxt-modules/icon#17]
Can update the Docs with color props.

 < Icon name="uil:github" size="50" color="green" />

**Comment by Atinux** [comment]
No sure to understand, any extra attribute you give to Icon it forwarded to the underlying component.

**Comment by snowdream** [comment]
< Icon name="uil:github" size="50" fill="green" />

**Comment by ddahan** [comment]
I think I understand the meaning of the question. Naturally you would expect something like this to work because it's how you fill a SVG:

```
< Icon name="uil:github" size="50" fill="green" />
```

But it does not. The correct way to do it is pass the `color` attribute, which may not be obvious to everyone, hence the issue.
