### ISSUE TITLE
Feature: Possible to change the icons directory

### ISSUE THREAD

**Issue by memic84** [nuxt-modules/icon#18]
Is it possible to change the `/components/global` directory. I have checked the code of this module, but it seems to me that it could be something that's inside Nuxt 3?

Proposition:
```js
  nuxtIcon: {
    size: "16px",
    source: '~/components/icons' // or an array with multiple values
  },
```

**Comment by Atinux** [comment]
The only requirement is that the component is defined as global, thus the `components/global/`

You can set a component to be global by using the `nuxt.config`:

```ts
export default defineNuxtConfig({
  components: [
    { path: '~/components/icons', global: true ],
    '~/components',
  }
})
```

See live demo on https://stackblitz.com/edit/nuxt-icon-playground-gyhf3n?file=nuxt.config.ts

**Comment by memic84** [comment]
Great, this works!

This can be closed, just a note from working with config extend.

I had to make an change for my setup with a monorepo and a config extends: 

```javascript
components: [
	{ 
		path: './components/icons', global: true 
	}, 
	'./components'
]
```

The `~` notation didn't work, and i had to change to use a `dot`.

The custom component in the `base` directory works, but in the root it doesn't work if i don't added the same code for the `nuxt.config.ts`. When adding duplicate code to `base` and `root` the components key, then it works. 

I might have the wrong concept here, but i thought that the `base` and `ui` config, components got merged (root being highest priority), so that the components configuration in nuxt.config, should already be there.

Example: [Reproduction](https://stackblitz.com/edit/github-rn8yee?file=nuxt.config.ts,base%2Fnuxt.config.ts&theme=dark)

**Comment by Atinux** [comment]
Any hint regarding the reproduction @danielroe ?

**Comment by danielroe** [comment]
Yes, this is correct. But `~` always points to the finally resolved source directory, and `~~` to the finally resolved root directory. So within a theme you plan to extend from, you should use relative imports.

We do plan to support _named_ layer aliases so you could do something like `~base/components` but that's next on the list: https://github.com/nuxt/framework/issues/3222.

**Comment by memic84** [comment]
@danielroe Thank you for the explanation and the extends feature is great in Nuxt 3!
