### ISSUE TITLE
Doesn't it work with nuxt 2 and nuxt bridge?

### ISSUE THREAD

**Issue by stephenjason89** [nuxt-modules/icon#21]
The docs did mention that this package is nuxt 3 ready.
I believe it was not mentioned that it isn't compatible with nuxt 2 and bridge

<img width="882" alt="image" src="https://user-images.githubusercontent.com/3810177/198713125-c9e6a002-bcaf-48de-b2d9-fbe7e08ffff0.png">

May I clarify if this is intended for nuxt 3 only?

Thank you

**Comment by szulcus** [comment]
It's hard to create a project compatible with Nuxt 2 and Nuxt 3, because they are very different from each other. Here you can preview if the module is compatible: https://modules.nuxtjs.org/?q=icon. If you need a solution for Nuxt 2 I recommend https://www.npmjs.com/package/@nuxtjs/svg-sprite.

**Comment by bmulholland** [comment]
For every module that has to be switched _at the same time_ as upgrading to Nuxt 3, it magnifies the effort and risk needed to make that upgrade. I wish more attention was put into making the upgrade path a smooth one.
