### ISSUE TITLE
Please add to readme file nuxt3 dynamic import 

### ISSUE THREAD

**Issue by ozgurkisa** [nuxt-modules/icon#22]
Please add to readme file nuxt3 dynamic import example:

```
import { Icon } from "@iconify/vue"

function renderIcon(icon) {
  return () => h(Icon, { icon })
}

renderIcon('uil:github')
```

**Comment by Atinux** [comment]
What is the use case?

**Comment by ozgurkisa** [comment]
> 

How to use javascript in Nuxt-Icon? I need this to be able to use render. (nuxt h)

For example create a link element in icon:
```
   h(
      NuxtLink,
            { to: { path: toPath } },
            { default: () =>  h(Icon, { icon })}
     )
```

**Comment by Atinux** [comment]
Hi @ozgurkisa 

You should be able to do:


```html
<script setup>
import { Icon } from '#components'
const icon = ref('uil:github')

const MyIcon = h(Icon, { name: 'uil:twitter' })
</script>

<template>
  <p><MyIcon /></p>
</template>
```

I updated the playground: https://stackblitz.com/edit/nuxt-icon-playground?file=app.vue

Can you confirm it works for you?

**Comment by ozgurkisa** [comment]
> Hi @ozgurkisa
> 
> You should be able to do:
> 
> ```
> <script setup>
> import { Icon } from '#components'
> const icon = ref('uil:github')
> 
> const MyIcon = h(Icon, { name: 'uil:twitter' })
> </script>
> 
> <template>
>   <p><MyIcon /></p>
> </template>
> ```
> 
> I updated the playground: https://stackblitz.com/edit/nuxt-icon-playground?file=app.vue
> 
> Can you confirm it works for you?

Yes, thank u. It might be good for you to add this to the readme file.

**Comment by Atinux** [comment]
Done, thank you @ozgurkisa
