### ISSUE TITLE
Remove default styles and make it headless

### ISSUE THREAD

**Issue by fayazara** [nuxt-modules/icon#24]
I see that there are a few default styles added in this, which actually make the icons behave differently than it should. 
https://github.com/nuxt-modules/icon/blob/4ecfd3a4672505799aa040176da9bf737f6b5f9a/src/runtime/Icon.vue#LL56-L61C2

```html
<style scoped>
.icon {
  display: inline-block;
  vertical-align: middle;
}
</style>
```

**Comment by Atinux** [comment]
Actually it was to stay consistent when using an emoji for example.

Removing the style will be a breaking change.

What about having an `headless` option in the `app.config.ts`?

**Comment by fayazara** [comment]
> Actually it was to stay consistent when using an emoji for example.
> 
> Removing the style will be a breaking change.
> 
> What about having an `headless` option in the `app.config.ts`?

@Atinux - Here's a PR https://github.com/nuxt-modules/icon/pull/32
