### ISSUE TITLE
Using two part component name

### ISSUE THREAD

**Issue by pi0** [nuxt-modules/icon#3]
I know `<Icon>` is much sexier than `<NuxtIcon>` or `<NIcon>` but maybe in order to avoid conflicting we can prefix component name too?

**Comment by productdevbook** [comment]
NIcon -> https://www.naiveui.com/en-US/os-theme/components/icon

**Comment by Atinux** [comment]
I like NuxtIcon but god I wish we can only keep Icon 😜

**Comment by productdevbook** [comment]
Ncon :D

**Comment by joshwcorbett** [comment]
Would love to use just `<Icon />`, for full consistency with `@iconify/vue`

**Comment by pi0** [comment]
Let's keep Icon 👍🏼
