### ISSUE TITLE
Invalid icon name causes Nuxt SSR to hang forever

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-modules/icon#30]
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.14.0`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

Reproduction: https://stackblitz.com/edit/nuxt-icon-playground-uffcst?file=app.vue

Seems to be an upstream issue with @iconify/vue, have created an issue there

**Comment by cyberalien** [comment]
Fixed in `@iconify/vue@4.0.1`. Thanks a lot for reporting!
