### ISSUE TITLE
Icons not render in SSR side (Node)

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/icon#35]
Icons are not being rendered in the SSR part

![image](https://user-images.githubusercontent.com/77386602/208881867-6d018869-b53b-493d-a0af-1370788189dd.png)

Source Code
![image](https://user-images.githubusercontent.com/77386602/208882403-ea70705d-7088-4fbf-a94f-ce5a5c549006.png)

In the Vue part (client) it works correctly

npx nuxi info
`- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.3.1`, `@nuxtjs/tailwindcss@6.1.3`, `formidable@2.1.1`, `@nuxtjs-alt/auth@2.1.6`, `@nuxtjs-alt/http@1.5.4`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.6.0`, `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.6`
- Build Modules:    `-`
`

**Comment by Atinux** [comment]
Can you share a Stackblitz please @agracia-foticos ?

**Comment by agracia-foticos** [comment]
solved
