### ISSUE TITLE
Type errors in vue-tsc

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt-modules/icon#43]
I'm suddenly getting type errors in `nuxt-icon` when linting my project.

<img width="1285" alt="Screenshot 2023-01-17 at 19 30 16" src="https://user-images.githubusercontent.com/2703233/212994483-f338ef52-43be-4832-9261-1f3da0be2cb2.png">

See check here: https://github.com/toniengelhardt/merklin/actions/runs/3942618884/jobs/6746483752

**Comment by Atinux** [comment]
Sorry about this @toniengelhardt 

Can you upgrade to [v0.2.6](https://github.com/nuxt-modules/icon/releases/tag/v0.2.6) ?

**Comment by toniengelhardt** [comment]
> Sorry about this @toniengelhardt
> 
> Can you upgrade to [v0.2.6](https://github.com/nuxt-modules/icon/releases/tag/v0.2.6) ?

Amazing, thanks for the super-fast fix! 🙏🏽

**Comment by toniengelhardt** [comment]
@Atinux I think the error is back in `0.2.10`

![Screenshot 2023-01-30 at 12 05 18](https://user-images.githubusercontent.com/2703233/215472599-407bfe6c-dbda-4298-a6a5-31b3bbc82f2a.png)
