### ISSUE TITLE
 ERROR  Could not load \node_modules\@iconify\vue\dist\iconify

### ISSUE THREAD

**Issue by glebsergeevich** [nuxt-modules/icon#49]
Is it not enough to use documentation steps to use it? 

https://nuxt.com/modules/icon#setup-%EF%B8%8F

```
  //package.json
  "devDependencies": {
    "nuxt-icon": "^0.2.10",
  },
```

```
    //nuxt.config.ts
    modules: [
        'nuxt-icon',
    ],
```

when I use `yarn generate` I got an error

`
ERROR  Could not load \node_modules\@iconify\vue\dist\iconify
`

if I install it by `yarn add --dev @iconify/vue` it's doesn't help

when I use `yarn dev` I have no any issue

**Comment by glebsergeevich** [comment]
my mistake. my IDE imported this automatically `@iconify\vue\dist\iconify` when I wrote the code, I didn't notice this line in one of the components because I didn't write it

**Comment by Alzy** [comment]
I don't understand. What was the fix? I am currently facing this exact error

**Comment by glebsergeevich** [comment]
Look at the top of the <script> section. Or find "import" on the page. In my case, the IDE was just importing a non-existent module and I was catching this error until I removed the "import" line.
