### ISSUE TITLE
error TS2339: Property 'nuxtIcon' does not exist on type 'AppConfig'.

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt-modules/icon#50]
The same of, but with newer version: 
Error something on nuxt 3.1.0 - ERROR(vue-tsc) Property 'nuxtIcon' does not exist on type 'AppConfig'. #46 

![Captura de tela de 2023-02-06 16-21-23](https://user-images.githubusercontent.com/379850/217065173-15ef73cb-8443-4a15-933c-fb3bc293cce1.png)
`node_modules/.pnpm/nuxt-icon@0.2.10/node_modules/nuxt-icon/dist/runtime/Icon.vue:34:40`
------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `ssr`, `runtimeConfig`, `app`, `modules`, `directus`, `meilisearch`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.1`, `nuxt-directus@3.2.2`, `nuxt-meilisearch@0.1.7`, `nuxt-icon@0.2.10`
- Build Modules:    `-`
------------------------------

My all packages: 
```
dependencies:
@nuxtjs/robots 3.0.0       apexcharts 3.37.0          moment 2.29.4              swiper 9.0.3               vue3-apexcharts 1.4.1      
@nuxtjs/tailwindcss 6.3.1  axios 1.3.2                nuxt-directus 3.2.2        type-check 0.4.0           yarn-upgrade-all 0.7.2     
@vueuse/core 9.12.0        daisyui 2.50.0             sanitize-html 2.9.0        vue-instantsearch 4.8.2    

devDependencies:
@commitlint/cli 17.4.2                   @typescript-eslint/parser 5.51.0         eslint-plugin-prettier 4.2.1             nuxt-icon 0.2.10                         
@commitlint/config-conventional 17.4.2   @vue/eslint-config-standard 8.0.1        eslint-plugin-vue 9.9.0                  nuxt-meilisearch 0.1.7                   
@types/cypress 1.1.3                     eslint 8.33.0                            husky 8.0.3                              prettier 2.8.3                           
@types/sanitize-html 2.8.0               eslint-config-prettier 8.6.0             lint-staged 13.1.0                       typescript 4.9.5                         
@typescript-eslint/eslint-plugin 5.51.0  eslint-plugin-nuxt 4.0.0                 nuxt 3.1.2                               vue-tsc 1.0.24  
```

**Comment by albericobenhur** [comment]
I have the same isue

**Comment by Tahul** [comment]
Hello @albericobenhur & @hermesalvesbr ;

I made another publish of the lib, the line you mentioned seem outdated:
https://github.com/nuxt-modules/icon/blob/e040a2c2f2f5cc9b813b706f4600c6979ae03ea5/src/runtime/Icon.vue#L13

The first `?.` should avoid `vue-tsc` to throw on this one.

Could you keep me updated if this `0.2.11` version fixes it?

**Comment by hermesalvesbr** [comment]
Thanks for your attention, but didn't work with 0.2.11
![Captura de tela de 2023-02-07 11-12-38](https://user-images.githubusercontent.com/379850/217268601-9744ecc7-bf2b-4786-abbb-ef1c9ed952f4.png)

```
dependencies:
@nuxtjs/robots 3.0.0       apexcharts 3.37.0          moment 2.29.4              swiper 9.0.3               vue3-apexcharts 1.4.1      
@nuxtjs/tailwindcss 6.3.1  axios 1.3.2                nuxt-directus 3.2.2        type-check 0.4.0           yarn-upgrade-all 0.7.2     
@vueuse/core 9.12.0        daisyui 2.50.0             sanitize-html 2.9.0        vue-instantsearch 4.8.2    

devDependencies:
@commitlint/cli 17.4.2                   eslint 8.33.0                            nuxt 3.1.2                               
@commitlint/config-conventional 17.4.2   eslint-config-prettier 8.6.0             nuxt-icon 0.2.11                         
@types/cypress 1.1.3                     eslint-plugin-nuxt 4.0.0                 nuxt-meilisearch 0.1.7                   
@types/sanitize-html 2.8.0               eslint-plugin-prettier 4.2.1             prettier 2.8.3                           
@typescript-eslint/eslint-plugin 5.51.0  eslint-plugin-vue 9.9.0                  typescript 4.9.5                         
@typescript-eslint/parser 5.51.0         husky 8.0.3                              vue-tsc 1.0.24                           
@vue/eslint-config-standard 8.0.1        lint-staged 13.1.0                    
```

**Comment by Tahul** [comment]
Is this project a public repository?

I double-checked again, and I don't understand why wouldn't you have the first `?.`, the built output has this:
<img width="356" alt="CleanShot 2023-02-07 at 16 11 22@2x" src="https://user-images.githubusercontent.com/1385263/217283756-3e6e2036-2938-4c72-838b-ce69609381af.png">

**Comment by hermesalvesbr** [comment]
I made a clean project and works fine. It's not a module bug. 

Maybe some cache by some package.

**Comment by MartCube** [comment]
Hi @hermesalvesbr, would you like to share how you clean your project to avoid this problem ?

**Comment by frasza** [comment]
@Atinux  Same error for me using Node 16.18 and Nuxt 3.3

**Comment by frasza** [comment]
@Atinux Sure, done -- https://github.com/nuxt-modules/icon/issues/62. Let  me know if I can assist further.
