### ISSUE TITLE
Nuxt Islands can't render <Icon>

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-modules/icon#52]
Reproduction: https://stackblitz.com/edit/nuxt-starter-cmr8kq?file=pnpm-lock.yaml

Most likely a Nuxt Islands limitation but issue here for tracking

**Comment by Atinux** [comment]
Do you have any idea what can go wrong with the component?

**Comment by toniengelhardt** [comment]
I'm not sure if it is related, but I'm getting type errors again with the `size` property:

![Screenshot 2023-02-14 at 10 33 33](https://user-images.githubusercontent.com/2703233/218710715-cc7f988b-30e0-4f5c-8ca5-c5bebc8c0284.png)

**Comment by harlan-zw** [comment]
This actually seems to be working correctly now, closing.
