### ISSUE TITLE
Suggestion: Icon -> NuxtIcon or BaseIcon

### ISSUE THREAD

**Issue by TechAkayy** [nuxt-modules/icon#58]
It might be a good idea to call the <Icon.../> component as <NuxtIcon.../> or <BaseIcon.../> instead by default. 

Are these alternate component name already available as aliases when using the nuxt-icon module?

**Comment by snowdream** [comment]
NuxtIcon seems better BaseIcon.

**Comment by Atinux** [comment]
See the discussion on https://github.com/nuxt-modules/icon/issues/3
