### ISSUE TITLE
Position icon vertically in line with text

### ISSUE THREAD

**Issue by some-user123** [nuxt-modules/icon#61]
I'm using nuxt-icon and would like to have icons in my text. They should behave like a normal letter and should be vertically aligned with other letters.

Example:
```html
X <Icon name="ic:baseline-home" /> x
```

is displayed like this:
![image](https://user-images.githubusercontent.com/74715856/225296269-f7a256b7-2a32-4735-84de-06bb57f0e1a7.png)

As you can see, the icon is positioned too low. Too me this does not seem nice. I would like it at the same position as the x or X, not below. Can this be done using this component?

**Comment by Atinux** [comment]
I believe you need to handle this yourself @some-user123 

You can use multiple solution in CSS in order to achieve this.

**Comment by codesinging** [comment]
`vertical-align: -0.125em;`
