### ISSUE TITLE
Do not work on Nuxt 3 "^3.4.1" 

### ISSUE THREAD

**Issue by FilipeBorges1993** [nuxt-modules/icon#69]
So i did 

![Screenshot 2023-04-21 at 11 48 17](https://user-images.githubusercontent.com/17275944/233617717-661c6846-cce8-499b-be40-50eb95f2b3fc.png)

Than 
![Screenshot 2023-04-21 at 11 51 38](https://user-images.githubusercontent.com/17275944/233618350-66048c8b-bcb4-4cb9-8866-6ffcb83c48dd.png)

And got
<img width="1343" alt="Screenshot 2023-04-21 at 11 51 19" src="https://user-images.githubusercontent.com/17275944/233618302-03670864-a40c-43d4-a650-f6a3aa676de0.png">

**Comment by Atinux** [comment]
Could you share a reproduction? It works well on my end

**Comment by tobychidi** [comment]
> So i did
> 
> ![Screenshot 2023-04-21 at 11 48 17](https://user-images.githubusercontent.com/17275944/233617717-661c6846-cce8-499b-be40-50eb95f2b3fc.png)
> 
> Than ![Screenshot 2023-04-21 at 11 51 38](https://user-images.githubusercontent.com/17275944/233618350-66048c8b-bcb4-4cb9-8866-6ffcb83c48dd.png)
> 
> And got <img alt="Screenshot 2023-04-21 at 11 51 19" width="1343" src="https://user-images.githubusercontent.com/17275944/233618302-03670864-a40c-43d4-a650-f6a3aa676de0.png">

The package is `nuxt-icon` and not `nuxt-icons`
