### ISSUE TITLE
spin, pulse, or other animations

### ISSUE THREAD

**Issue by ricky11** [nuxt-modules/icon#7]
Font awesome supports tags that animate the icon

spin & pulse are some examples.

Anyway we can support these?

Thanks

**Comment by minstn** [comment]
+1 would be amazing to have that

**Comment by Atinux** [comment]
Could you give an example of usage? (sorry for late answer)

**Comment by ricky11** [comment]
> Could you give an example of usage? (sorry for late answer)

https://fontawesome.com/v5/docs/web/style/animate

By adding a tag "spin" or "pulse" font awesome would add some css styles to the element

i.e. <fa icon="spinner" spin size="2x" />

my guess is that would need to add the css styles for this manually.

Rishi

**Comment by Atinux** [comment]
What about creating a `spin` class directly?

See example: https://stackblitz.com/edit/nuxt-icon-spinner?file=app.vue
