### ISSUE TITLE
error TS7053: Element implicitly has an 'any' type because expression of type '(string & {}) | "nuxt"' can't be used to index type '{ nuxt: string; }'.

### ISSUE THREAD

**Issue by devbyP** [nuxt-modules/icon#71]
this error occur when I build the project
```

error TS7053: Element implicitly has an 'any' type because expression of type '(string & {}) | "nuxt"' can't be used to index type '{ nuxt: string; }'.

28 const iconName = computed(() => (appConfig.nuxtIcon?.aliases || {})[props.name] || props.name)
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/nuxt-icon/dist/runtime/Icon.vue:28

```
![Screenshot 2566-04-25 at 19 45 48](https://user-images.githubusercontent.com/82090783/234280626-1548f4ea-144c-450e-8516-7cf5cbac9ef2.png)

my setting
![Screenshot 2566-04-25 at 19 39 35](https://user-images.githubusercontent.com/82090783/234279549-08570abe-bbca-48af-934d-10da77ac5935.png)

![Screenshot 2566-04-25 at 19 39 23](https://user-images.githubusercontent.com/82090783/234278984-627aeeb8-c49c-47e9-9cc9-00a9f8b55d73.png)

![Screenshot 2566-04-25 at 19 41 23](https://user-images.githubusercontent.com/82090783/234279531-d5f06052-b8f8-4dd9-8efd-27fa633909d6.png)

**Comment by Atinux** [comment]
Should be fixed with latest version of the module and Nuxt.
