### ISSUE TITLE
nuxt-icon breaks type extension of AppConfigInput?

### ISSUE THREAD

**Issue by jontybrook** [nuxt-modules/icon#72]
Nuxt version: 3.4.2
nuxt-icon version: 0.4.0
Package manager: pnpm

I'm working on a brand new nuxt project today. I just installed nuxt-icon@0.4.0, and I started getting type errors like this in my app.config.ts:

![screenshot_000134-4Vbu3Zpb_25-04-2023_20h31m25s](https://user-images.githubusercontent.com/542319/234383889-6fe2df9a-54b1-4d6c-b9eb-55eff00d1a5d.png)

Removing nuxt-icon from my nuxt modules resolves this. Seems nuxt-icon is breaking dynamic types?

Not sure if this could be related to: https://github.com/nuxt/nuxt/pull/20440 ?

**Comment by Atinux** [comment]
We are working on it with @danielroe , you can ignore the error for now (it's TS only)

**Comment by Atinux** [comment]
Could you test with `nuxt-edge` @jontybrook ?

https://nuxt.com/docs/guide/going-further/edge-channel/#edge-release-channel
