### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by rowild** [nuxt-modules/icon#73]
In the Vue section of the Readme 
https://nuxt.com/modules/icon#vue-component

there is a link to an example:
https://nuxt.com/modules/playground/components/global/NuxtIcon.vue

but that one does not work.

Would love to provide a PR, but I cannot find the proper link...

**Comment by Atinux** [comment]
Thank you, should be fixed in some minutes on the website

**Comment by liuzemei** [comment]
It's fixed?

**Comment by liuzemei** [comment]
I use latest v2 branch version, and update nuxt-icon to 0.5.0, but it don't works.
