### ISSUE TITLE
Feature Request - support for i-mdi-home "unocss" format

### ISSUE THREAD

**Issue by TechAkayy** [nuxt-modules/icon#84]
Nuxt-Icon currently follows `mdi:home` which is `iconify` format. 

Nuxtlabs/ui follows `i-mdi-home` which is `unocss` format.

Icones, unocss support using multiple formats. 
![image](https://github.com/nuxt-modules/icon/assets/73772701/16ee6d30-c03f-45e9-9811-fc8ecd696c42)

Would be great to have support to use `unocss` format in Nuxt-Icon in addition to the current `iconify` format, so that it can be used when working on other libraries which uses the "unocss" format.

**Comment by Atinux** [comment]
We actually use `@iconify/vue` to load the icon with the name: https://github.com/nuxt-modules/icon/blob/022d563466c6782159a8295714536ed98a1e563a/src/runtime/Icon.vue#L53

It does support `mdi:home` and `mdi-home` so I guess we can add a way to remove `i-` prefix to support `unocss` format.

**Comment by TechAkayy** [comment]
Any chance this could be prioritised if its not too hard 🫠
