### ISSUE TITLE
error TS2339: Property 'aliases' does not exist on type '{}'

### ISSUE THREAD

**Issue by some-user123** [nuxt-modules/icon#86]
Details in this (closed) issue: https://github.com/nuxt-modules/icon/issues/62

**Comment by Me-Phew** [comment]
One workaround could be to add this to the `app.config.ts`

`nuxtIcon: {
    aliases: undefined,
    class: undefined,
    size: undefined,
  },`

**Comment by jamesray** [comment]
@Atinux any updates on this issue? We're using nuxt-icon in production and this is something we're hoping to not need to create a workaround for.

**Comment by stephiescastle** [comment]
> One workaround could be to add this to the `app.config.ts`
> 
> `nuxtIcon: { aliases: undefined, class: undefined, size: undefined, },`

Thanks @Me-Phew! This worked as a temporary fix and allows us to keep typeCheck enabled for everything else.

**Comment by Me-Phew** [comment]
Are you also getting [this error](https://github.com/nuxt-modules/icon/issues/92)?

**Comment by zllvm** [comment]
> Are you also getting [this error](https://github.com/nuxt-modules/icon/issues/92)?

You could add `index.d.ts` to temporarily solve it as it is mentioned in [pull#63](https://github.com/nuxt-modules/icon/pull/63):

```
// workaround for https://github.com/nuxt-modules/icon/pull/63
import * as _nuxt_schema from '@nuxt/schema'

interface NuxtIconModuleOptions {
  size?: string | false
  class?: string
  aliases?: { [alias: string]: string }
}

declare module '@nuxt/schema' {
  interface AppConfig {
    nuxtIcon?: NuxtIconModuleOptions
  }
}
```

**Comment by Me-Phew** [comment]
> > Are you also getting [this error](https://github.com/nuxt-modules/icon/issues/92)?
> 
> You could add `index.d.ts` to temporarily solve it as it is mentioned in [pull#63](https://github.com/nuxt-modules/icon/pull/63) by [luke-z](https://github.com/luke-z):
> 
> ```
> // workaround for https://github.com/nuxt-modules/icon/pull/63
> import * as _nuxt_schema from '@nuxt/schema'
> 
> interface NuxtIconModuleOptions {
>   size?: string | false
>   class?: string
>   aliases?: { [alias: string]: string }
> }
> 
> declare module '@nuxt/schema' {
>   interface AppConfig {
>     nuxtIcon?: NuxtIconModuleOptions
>   }
> }
> ```

It works, thanks!

**Comment by gaomingzhao666** [comment]
> > Are you also getting [this error](https://github.com/nuxt-modules/icon/issues/92)?
> 
> You could add `index.d.ts` to temporarily solve it as it is mentioned in [pull#63](https://github.com/nuxt-modules/icon/pull/63) by [luke-z](https://github.com/luke-z):
> 
> ```
> // workaround for https://github.com/nuxt-modules/icon/pull/63
> import * as _nuxt_schema from '@nuxt/schema'
> 
> interface NuxtIconModuleOptions {
>   size?: string | false
>   class?: string
>   aliases?: { [alias: string]: string }
> }
> 
> declare module '@nuxt/schema' {
>   interface AppConfig {
>     nuxtIcon?: NuxtIconModuleOptions
>   }
> }
> ```

**It still works in may 2024, at the meantime this error is still here when project is building**

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by some-user123** [comment]
Is this sufficient?
https://github.com/mandragora-hub/nuxt-icon-repro-build-bug
