### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by Me-Phew** [nuxt-modules/icon#92]
Nuxt-icon: 0.4.2
Nuxt: 3.6.5

node_modules/nuxt-icon/dist/runtime/Icon.vue:29:33 - error TS7053: Element implicitly has an 'any' type because expression of type 'string & {}' can't be used to index type '{}'.

29 const iconName = computed(() => (appConfig.nuxtIcon?.aliases || {})[props.name] || props.name)

**Comment by Atinux** [comment]
Closing in favour of #86
